# Creación y manejo de Pivot Tables en pandas

## ¿Qué son las Pivot Tables en pandas?

Las Pivot Tables son una herramienta poderosa y versátil que nos permite resumir y reorganizar columnas de datos crudos de un DataFrame de pandas. Gracias a ellas, podemos realizar cálculos estadísticos comunes como sumas, conteos y promedios, ayudándonos a descubrir patrones ocultos y obtener insights valiosos de nuestros datos originales.

Al utilizar Pivot Tables, puedes:

* Resumir y reorganizar los datos.
* Identificar patrones.
* Comparar subgrupos de datos.

## ¿Cómo crear una Pivot Table?

Para crear una Pivot Table en pandas, debes seguir un proceso estructurado, especificando varios parámetros clave. Veamos cómo hacerlo paso a paso.

## ¿Cómo pasar la información al DataFrame?

El primer paso es definir el DataFrame que vamos a utilizar. Luego, especificaremos las columnas y los índices que deseamos tener en nuestra Pivot Table.

1. **DataFrame inicial:** Debemos tener un DataFrame con los datos que queremos analizar.
2. **Columna de valores:** Definimos la columna cuyo cálculo estadístico queremos realizar (por ejemplo, 'cantidad').
3. **Índice:** En lugar de usar un índice posicional (como 0, 1, 2), se puede utilizar una de las columnas como índice. Por ejemplo, 'country'.
4. **Columnas:** Incluir las columnas que deseas evaluar, como los 'stock codes'.
5. **Función de cálculo:** Determina la función que aplicarás, como la suma, para mostrar las sumatorias totales en el índice.

In [1]:
import pandas as pd

data_frame = pd.read_csv('./online_retail.csv')
data_frame.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [2]:
# Crear una pivot table
pivot_table = pd.pivot_table(
    data_frame, 
    values='Quantity', 
    index='Country', 
    columns='StockCode', 
    aggfunc='sum'
)

# Mostrar la pivot table
pivot_table

StockCode,10002,10080,10120,10123C,10123G,10124A,10124G,10125,10133,10134,...,M,PADS,POST,S,gift_0001_10,gift_0001_20,gift_0001_30,gift_0001_40,gift_0001_50,m
Country,,,,,,,,,,,,,,,,,,,,,
Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,272.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Channel Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Denmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EIRE,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,NaN,...,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
European Community,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Finland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,372.0,NaN,10.0,NaN,NaN,NaN,NaN,470.0,NaN,NaN,...,-16.0,NaN,803.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,1.0,NaN,NaN,NaN,NaN,NaN,NaN,120.0,NaN,NaN,...,2.0,NaN,1104.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Greece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hong Kong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Iceland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Israel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.0,NaN,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Japan,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lebanon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lithuania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Malta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Netherlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-480.0,NaN,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Norway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,...,1.0,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Singapore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spain,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.0,NaN,209.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sweden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Switzerland,12.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,10.0,NaN,...,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Kingdom,615.0,495.0,183.0,-13.0,-38.0,16.0,17.0,686.0,2645.0,-19.0,...,3662.0,4.0,3328.0,-59.0,39.0,20.0,37.0,3.0,4.0,1.0
Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## ¿Cómo modificar las funciones agregadas?

Se pueden personalizar las funciones agregadas de nuestra Pivot Table según la necesidad del análisis.

En lugar de sumar, podemos calcular la media, por ejemplo:

In [3]:
# Modificar para utilizar la función de media
pivot_table = pd.pivot_table(
    data_frame, 
    values='Quantity', 
    index='Country', 
    columns='StockCode', 
    aggfunc='mean'
)

# Mostrar la pivot table con media
pivot_table

StockCode,10002,10080,10120,10123C,10123G,10124A,10124G,10125,10133,10134,...,M,PADS,POST,S,gift_0001_10,gift_0001_20,gift_0001_30,gift_0001_40,gift_0001_50,m
Country,,,,,,,,,,,,,,,,,,,,,
Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.642857,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.775510,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,...,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Channel Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Denmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.928571,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EIRE,12.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,...,-0.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
European Community,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Finland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,NaN,2.170732,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,46.50,NaN,10.000000,NaN,NaN,NaN,NaN,78.333333,NaN,NaN,...,-1.600000,NaN,2.581994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,1.00,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,NaN,...,0.125000,NaN,2.882507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Greece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hong Kong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Iceland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Israel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.000000,NaN,2.444444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Japan,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lebanon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lithuania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Malta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Netherlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-480.000000,NaN,2.538462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Norway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,2.850000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,...,0.071429,NaN,3.233333,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Singapore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spain,24.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.000000,NaN,3.370968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sweden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,NaN,1.541667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Switzerland,12.00,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,10.000000,NaN,...,NaN,NaN,2.939394,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Kingdom,10.25,20.625,6.310345,-3.25,-38.0,3.2,4.25,8.469136,13.704663,-19.0,...,7.661088,1.0,23.111111,-0.936508,4.333333,2.0,4.625,1.0,1.0,1.0
Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## ¿Cómo apilar y desapilar datos en DataFrames?

El apilamiento y desapilamiento de datos son técnicas útiles cuando necesitas cambiar la estructura de tu DataFrame para análisis más profundos o para ajustar la presentación de la información.

## ¿Qué es el método stack en pandas?

El método `stack` convierte el índice de un DataFrame en una columna, apilando los datos.

In [4]:
# Usar el método stack para apilar datos
stacked_df = data_frame.stack()

# Mostrar el DataFrame apilado
stacked_df

0       InvoiceNo                                  536365
        StockCode                                  85123A
        Description    WHITE HANGING HEART T-LIGHT HOLDER
        Quantity                                        6
        InvoiceDate                   2010-12-01 08:26:00
                                      ...
541908  Quantity                                        3
        InvoiceDate                   2011-12-09 12:50:00
        UnitPrice                                    4.95
        CustomerID                                12680.0
        Country                                    France
Length: 4198738, dtype: object

## ¿Qué es el método unstack en pandas?

El `unstack` hace el proceso contrario al `stack`, transformando columnas en índices.

In [5]:
# Usar el método unstack para desapilar datos
unstacked_df = stacked_df.unstack()

# Mostrar el DataFrame desapilado
unstacked_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.1,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

## Un paso más allá con Pivot Tables

Las Pivot Tables y los métodos de apilar y desapilar ofrecen posibilidades casi ilimitadas para el análisis de datos. Ahora no solo estás limitado a índices posicionales; puedes modificar y utilizar columnas para un análisis más profundo y personalizado.